/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * sender.java
 *
 * Created on 11-Nov-2011, 13:20:22
 */
package chatApplication;
import java.net.*;
import javax.swing.*;
import java.util.StringTokenizer;
import java.util.ArrayList;


/**
 *
 * @author B&E
 */
public class sender extends javax.swing.JFrame {

    /** Creates new form sender */
    public sender() {
        initComponents();
        
        
        try{
    sendSocket = new DatagramSocket();
        }catch(Exception e){}
        lstModel= new DefaultListModel();
         names = new ArrayList<String>();
        jList1.setModel(lstModel);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMsg = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtPrivate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtb = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Connect");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Disconnect");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Nickname:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("Room Chat");

        txta.setColumns(20);
        txta.setRows(5);
        jScrollPane1.setViewportView(txta);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setText("Users");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel4.setText("Private");

        jButton4.setText("Send");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtb.setColumns(20);
        txtb.setRows(5);
        jScrollPane3.setViewportView(txtb);

        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtPrivate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton4))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(jLabel3))))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jButton1)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(txtPrivate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

System.out.println("txtname:"+txtname.getText());
String s = 1+"*"+txtMsg.getText()+"*"+txtname.getText();
sendData = s.getBytes();
length = s.length();
 
try{
    String host="localhost";
    InetAddress IPAddress = InetAddress.getByName(host);
    sendPacket = new DatagramPacket(sendData,length,IPAddress,9898);
    
    sendSocket.send(sendPacket);
}catch(Exception e){}

txtMsg.setText(""); 
            
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    
String s = 3+"*"+txtname.getText();
sendData = s.getBytes();

 System.out.println(s);
int length = s.length();
int port = 9898;
 String host="localhost";
 

try{
    InetAddress IPAddress = InetAddress.getByName(host);
    sendPacket = new DatagramPacket(sendData,length,IPAddress,port);
    sendSocket.send(sendPacket);
}catch(Exception e){}

 


 

Thread th = new Thread() {
    public void run(){
           while(true){
           
           try{
             
               receivePacket = new DatagramPacket(receiveData,receiveData.length);
               
                  sendSocket.receive(receivePacket);
                
                   receivedMessage = new String(receivePacket.getData(),0,receivePacket.getLength());
                  
                  StringTokenizer rcvMessage= new StringTokenizer(receivedMessage,"*");
                    
                    String name = rcvMessage.nextToken();
               
                    String msgId=rcvMessage.nextToken();
                 
                    int id = Integer.parseInt(msgId);
                    
                    if(id==1){
                       // received broadcast message
                         String message = rcvMessage.nextToken();
                         txta.append(name+": "+message+"\n");
                    }
                    else if(id==3){
                        
                    if(name.equals("0")){
                        JOptionPane.showMessageDialog(rootPane, "Please choose another Nickname");
                        jButton2.setEnabled(true);
                        break;
                        
                    }
                    
                    else if(lstModel.getSize()==0){
                        lstModel.addElement(name);
                        
                     
                    }
                    
                    else{ 
                        boolean found=false;
                          for(int i=0;i<lstModel.getSize();i++)
                          {
                              String s= lstModel.getElementAt(i).toString();
                             
                              if(name.equals(s))
                                  {
                                
                                  found=true;
                                  break;
                              }
                              
                              
                          }
                          if(found==false){
                          lstModel.addElement(name);
                          }
                        }
             
                      
                      
                  
                    }
                    
                    else if(id==4){
                        
                        
                      
                          
                            
                            for(int i=0;i<lstModel.getSize();i++){
                              String s= lstModel.getElementAt(i).toString();
                              if(name.equals(s)){
                                  lstModel.removeElementAt(i);
                                  jButton2.setEnabled(true);
                                  break;
                              }
                            }
                        
                    }
                    
                    else if(id==6){
                        String from = rcvMessage.nextToken();
                        txtb.append(from+": "+name+"\n");
                    }
                    
               }catch(Exception e){}
       
                
           }//while
           
        
          
    }//run
   
};

th.start();
 
 //txtname.setText("");
 jButton2.setEnabled(false);
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 String s = 4+"*"+txtname.getText();
 sendData = s.getBytes();
int length = s.length();
int port = 9898;
 String host="localhost";
 

try{
    InetAddress IPAddress = InetAddress.getByName(host);
    sendPacket = new DatagramPacket(sendData,length,IPAddress,port);
  
    sendSocket.send(sendPacket);
}catch(Exception e){}
 
  jButton3.setEnabled(false);
  System.exit(0);
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 int index = jList1.getLeadSelectionIndex();
 String to=lstModel.getElementAt(index).toString();
 String from = txtname.getText();
 
 String message = 2+"*"+txtPrivate.getText()+"*"+from+"*"+to;
 sendData = message.getBytes();
 
 int length = message.length();
int port = 9898;
 String host="localhost";
 

try{
    InetAddress IPAddress = InetAddress.getByName(host);
    sendPacket = new DatagramPacket(sendData,length,IPAddress,port);
 
    sendSocket.send(sendPacket);
}catch(Exception e){}
 txtPrivate.setText("");
}//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new sender().setVisible(true);
            }
        });
    }
    DatagramSocket sendSocket;
     DatagramPacket receivePacket,sendPacket;
     byte[] sendData= new byte [1024];
     byte[] receiveData = new byte [1024];
     int length,port;
      String receivedMessage;
    private javax.swing.DefaultListModel lstModel;
    private  ArrayList<String> names;
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtMsg;
    private javax.swing.JTextField txtPrivate;
    private javax.swing.JTextArea txta;
    private javax.swing.JTextArea txtb;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
